About page
awaisanwar544/rr-workshop pull request #1
Opened 2022-02-02 21:03 UTC by awaisanwar544

Add these feature

1. The home page.
2. The about page.
3. Mobile: up to 768px wide.
4. Desktop: 768px or wider.

2022-02-02 23:50 UTC, awaisanwar544 commented
### Important Note

I am using Bootstrap and included it in the project using package manager (npm) and used sass to customize bootstrap variables. It resulted in more than 1500 sylelintrc errors because  `main.css` is coming from sass compiler and I've only written `main.scss`. To solve this issue I added `main.css` in ignore list of stylelintrc in this commit. [2c4b862](https://github.com/awaisanwar544/rr-workshop/pull/1/commits/2c4b8624aa009dbc49897f0b468d260a122610db)

2022-02-03 01:01 UTC, micheaol requested changes
Hi @awaisanwar544 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!


## TO HIGHLIGHT: 

- Good video presentation 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 


## Suggested changes

- _Please check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-03 01:01 UTC, micheaol commented on about.html
> +                </div>
Please ensure you have all the features (like `header`, `hero-section`, `feature-speakers`, and `program-section`) in just one branch (`about-page`) because having them in separate branches will not make your app perform as expected. If you need further clarification, please contact me on slack
example:
![expected](https://user-images.githubusercontent.com/10332499/152262543-a08bb4c6-858a-4ef7-9c21-2b0e452f0a89.PNG)

2022-02-03 01:01 UTC, micheaol commented on main.js
> +      org: 'Editor ResearchRoof',
Please ensure that this section includes six individual articles, each with an image, title, subtitle, and description according to the requirement.

2022-02-03 01:01 UTC, micheaol commented on index.html
> +                    <div class="card bg-light bg-opacity-10 align-items-center p-lg-2 flex-lg-column flex-row col-12">
- Please ensure that you make use of GitHub Pages to deploy the web pages.
- Please ensure the project is deployed properly, all pages, links, and images work as expected.
- Please ensure a link to the deployed project is present in the README in the branch you are sending for review.

2022-02-03 04:08 UTC, ShoiraTa requested changes
Hi @awaisanwar544 ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Video presentation is professional ✔️ 
- Descriptive Pull Request ✔️ 
- Professional commit history  ✔️ 
- The project is deployed properly, all pages, links, and images work as expected.   ✔️ 
- The project contains a `Home` page and `About` page.  ✔️ 
- The page is responsive  ✔️ 
- Amazing animation  ✔️ 
- The pages should look almost identical to the original design    ✔️ 
- HTML is semantic   ✔️ 
- JS file has a dynamic content  ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 04:08 UTC, ShoiraTa commented on index.html
> +                    <div class="card bg-light bg-opacity-10 align-items-center p-lg-2 flex-lg-column flex-row col-12">
- [x] As the previous reviewer mentioned, lets add a deployment link on GitHub Pages in readme file. I have noticed that curretly your page is not being updated on every commit in GitHubPages because it failed:
![image](https://user-images.githubusercontent.com/77038610/152279134-62da3388-60e8-4a09-9ccb-f612e2b169c9.png)
Please kindly fix this error

- [x] OPTIONAL: I have noticed that the `readme` currently is empty, I strongly suggest to update it and add all the data regarding the project. Please do not forget to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), in "acknowledgements" section

2022-02-03 09:31 UTC, awaisanwar544 commented
The site is deployed on Github pages and there is already a link in the readme file. See the screenshot below

<img width="875" alt="Screenshot 2022-02-03 at 2 04 02 PM" src="https://user-images.githubusercontent.com/87834222/152312595-c4d7b09b-b847-4b55-b818-49c994e66970.png">

2022-02-03 09:46 UTC, t-yanick approved these changes
Hi @awaisanwar544 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 14:55 UTC, merged